# Generated by Django 4.2.7 on 2024-01-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_skills_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='rating',
        ),
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '★☆☆'), (2, '★★☆'), (3, '★★★')], null=True),
        ),
    ]
