# Generated by Django 4.2.7 on 2024-01-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_skills_rating_alter_skills_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='git_hub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linked_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
