# Generated by Django 4.2.7 on 2024-01-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_git_hub_user_instagram_user_linked_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='git_hub',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linked_in',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
