# Generated by Django 4.2.7 on 2024-01-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_git_hub_alter_user_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_web',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
