# Generated by Django 4.2.7 on 2024-01-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cur_proj',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cur_proj_desc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cur_proj_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
