# Generated by Django 4.2.7 on 2024-01-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_cur_proj_desc_user_cur_project_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cur_project_desc',
            new_name='current_project_desc',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='cur_project_link',
            new_name='current_project_link',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='cur_project_name',
            new_name='current_project_name',
        ),
    ]
