# Generated by Django 4.2.7 on 2024-01-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_cur_project_desc_user_current_project_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_project_desc',
        ),
    ]
