# Generated by Django 4.2.7 on 2024-01-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickenmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_email',
            field=models.EmailField(default='sendermail', max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_name',
            field=models.CharField(default='sendername', max_length=100),
        ),
    ]
