# Generated by Django 4.2.7 on 2023-12-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_active',
        ),
    ]
