# Generated by Django 4.2.7 on 2023-12-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_userinfo_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
